"use client"
import { Inter } from 'next/font/google'
import './globals.css'
import { CategoryProvider } from '@/Context/CategoryContext'
import { CustomerProvider } from '@/Context/CustomerContext'
import { ProductProvider } from '@/Context/ProductContext'
import { CartProvider } from "react-use-cart";

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Ladu Smarat',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-[#FFF2E9]"}>
        <CustomerProvider>
          <ProductProvider>
            <CategoryProvider>
              <CartProvider>
                {children}
              </CartProvider>
            </CategoryProvider>
          </ProductProvider>
        </CustomerProvider>
      </body>
    </html>
  )
}
